#include <iostream>
#include <GenesisCore/Genesis.hpp>

#include <gtest/gtest.h>

namespace ge {
	namespace core {
		// Tests if a uuid generated by a uuid string is the same as the base uuid
		TEST(UUIDTest, ConvertingString) {
			ge::core::UUID a;
			ge::core::UUID b = ge::core::UUID::fromString(a.format());

			std::cout << a.format() << " == " << b.format() << std::endl;
			ASSERT_TRUE(a == b) << "UUID did not convert correctly from string!";
		}
		// Tests if a uuid generated by the handle of a base uuid is the same as the base
		TEST(UUIDTest, ConvertingHandle) {
			ge::core::UUID a;
			ge::core::UUID b = ge::core::UUID(a.getHandle());

			std::cout << a.format() << " == " << b.format() << std::endl;
			ASSERT_TRUE(a == b) << "UUID did not convert correctly from handle!";
		}
	}
}

int main(int argc, char** argv) {
	std::cout << "Starting Genesis Core Tests..." << std::endl;
	testing::InitGoogleTest(&argc, argv);
	return RUN_ALL_TESTS();
}
